projects:
  todoapi:
    schemaPath: amplify/backend/api/todoapi/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/services/API.ts
        docsFilePath: src/graphql
        region: us-west-2
        apiId: null
        maxDepth: 2
